#!/bin/bash
#
# Nectar VGPU driver check tool for MOTD
#
# Will pull the latest version of the driver from object storage and do some
# simple semver check to ensure the installed driver is up to date.
#

LATEST_URL=https://object-store.rc.nectar.org.au/v1/AUTH_2f6f7e75fc0f453d9c127b490b02e9e3/nvidia-vgpu-repo/current.json

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

# Semver comparison
verlte() { printf '%s\n' "$1" "$2" | sort -C -V; }
verlt() { ! verlte "$2" "$1"; }

# Fetch current version
latest_json=$(wget --timeout 5 -O- --content-on-error "$LATEST_URL" 2>/dev/null)
if [ $? -ne 0 ]; then
        echo "ERROR: Failed to fetch latest VGPU driver version!"
        exit 1
fi
latest_driver_ver=$(echo $latest_json | jq -r '.current_version.guest_driver.Linux')

# Get the installed version
installed_driver_ver=$(nvidia-smi --query-gpu=driver_version --format=csv,noheader 2>/dev/null)
# If the driver hasn't been able to be loaded at all, try getting the version
# from the package version instead
if [ $? -ne 0 ]; then
        installed_driver_ver=$(dpkg-query -W -f '${db:Status-Status} ${Package} ${Version}\n' 'nvidia-linux-grid-*' | awk '/^installed/ {print $3}')
fi

# Print version
echo
echo "NVIDIA VGPU driver versions:"
echo "  Required:  $latest_driver_ver"
echo "  Installed: ${installed_driver_ver:-"Not found"}"
echo

if verlt "$installed_driver_ver" "$latest_driver_ver"; then
    echo -e "${RED}ERROR: The NVIDIA VGPU driver is either not installed or out of date.${NC}"
    echo -e "${RED}You must update your driver by running the update-vgpu-driver command${NC}"
else
    echo -e "${GREEN}Installed NVIDIA VGPU driver version is OK${NC}"
fi
