---
- name: Install CVMFS release .deb package
  ansible.builtin.apt:
    deb: https://cvmrepo.s3.cern.ch/cvmrepo/apt/cvmfs-release-latest_all.deb

- name: Install CVMFS package
  ansible.builtin.apt:
    name: cvmfs
    state: latest
    update_cache: yes
