{
 "title": "System Metrics",
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{mode='idle'}[5m])) by (instance)",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes",
     "legendFormat": "RAM Usage"
    }
   ]
  },
  {
   "title": "GPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 11 },
   "targets": [
    { "expr": "nvidia_smi_gpu_utilization", "legendFormat": "GPU Usage" }
   ]
  }
 ]
}