---
# e.g. Debian 9 (Stretch) amd64
nectar_default_image_name: "{{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_major_version'] }} ({{ ansible_facts['distribution_release']|capitalize }}) {% if ansible_facts['architecture'] == 'x86_64' %}amd64{% else %}{{ ansible_facts['architecture'] }}{% endif %}"
