#!/bin/bash

#  Licensed under the Apache License, Version 2.0 (the "License"); you may
#  not use this file except in compliance with the License. You may obtain
#  a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#  License for the specific language governing permissions and limitations
#  under the License.

set -x

# Limitations
# 1. Cleanup (-c) is not selective.  It gets rid of all previous
#    CloudStore mounts and configs that it can find, for all users
#    with little feedback 
# 2. We don't deal with the case where the someone has set up a
#    CloudStor mount by hand in an unexpected location.
# 3. The mounted share is owned by the current user with access to
#    others restricted by the user's netmask.
# 4. Mount options are hard-wired
# 5. We don't deal with mounting more than one CloudStor share at
#    a time (for the entire instance.)

# CloudStor details
WEBDAV_URL=https://cloudstor.aarnet.edu.au/plus/remote.php/webdav/
MOUNT_PATH=/cloudstor

cleanup=false
username=
password=
mount_path=${MOUNT_PATH}

usage() {
  cat >&2 << EOF
Usage: $0 [options]

Options:
  -c     unmount and clean up any CloudStor config
  -u     username. if not given, you will be prompted
  -p     password. if not given, you will be prompted
  -m     mount-directory. defaults to $MOUNT_PATH
  -h     this help message
EOF
  exit 1
}

check_for_mount() {
  if mountpoint -q "$1"; then
    echo "A CloudStor share is already mounted at $1"
    echo "To unmount all shares and clean up all previous CloudStore configs"
    echo "and mount points, you can run '$0 -c'"  
    exit 2
  fi
}

delete_mount_point() {
  if [ $# -gt 0 ]; then
    if [ -d "$1" ]; then
      echo "Removing old mountpoint $1"      
      sudo rmdir "$1"
    fi
  fi
}
      
# Should run as unpriv user, so we can use that user in fstab
if [[ $UID == 0 ]]; then
  echo "This command should NOT be run as root"
  exit 1
fi


while getopts "hcu:p:m:" opt; do
  case ${opt} in
    h)
      usage
      ;;
    c)
      cleanup=true
      ;;
    u)
      username=${OPTARG}
      ;;
    p)
      password=${OPTARG}
      ;;
    m)
      mount_path=${OPTARG}
      if [ "${mount_path#/}" = "${mount_path}" ]; then
          echo "-m should give an absolute directory path"
          usage
      fi
      # Should also check for white-space in the path because
      # that is likely to mess up the fstab
      ;;
    *)
      usage
      ;;
    esac
done
shift $((OPTIND-1))

# Clean up all traces of all previous cloudstor mounts.  We cannot
# be selective because the secrets is common to all mounts.
if [ "$cleanup" = true ]; then
  echo "Cleaning up CloudStor setup..."
  if mountpoint -q "$mount_path"; then
    sudo umount "$mount_path"
  fi
  if mountpoint -q "$MOUNT_PATH"; then
    sudo umount "$MOUNT_PATH"
  fi
  grep -h "$WEBDAV_URL" /etc/fstab | {
    read URL MP REST
    if mountpoint -q "$MP"; then
      sudo umount "$MP"
    fi
    delete_mount_point "$MP"
  }
  sudo sed -i '\,^'"$WEBDAV_URL"',d' /etc/fstab
  [ -f /etc/davfs2/secrets ] && sudo sed -i '\,^'"$WEBDAV_URL"',d' /etc/davfs2/secrets
  delete_mount_point "$mount_path"
  delete_mount_point "$MOUNT_PATH"
  exit 0
fi

# Check for active cloudstor mounts
check_for_mount "$mount_path"
check_for_mount "$MOUNT_PATH"

# Deal with cases where cloudstor is or was mounted on some
# other mount point (as recorded in the fstab).
grep -h "$WEBDAV_URL" /etc/fstab | {
  read URL MP REST
  if [ $# -gt 0 ]; then
    if [ "X$mount_path" != "X$MP" ] ; then
      check_for_mount "$MP" || {
        echo "CloudStor was previously mounted at $MP"
        echo "To clean up all previous CloudStore mount configs"
        echo "and mount points, you need to run '$0 -c'"
      }
      exit 2
    fi
  fi
}
if [ $? -eq 2 ] ; then
  exit 2
fi

  cat << EOF
This command guides you through the process of mounting your AARNet CloudStor
storage to your Nectar instance.

To mount your CloudStor storage, you will be prompted for a username and
password. You can generate specific use 'app passwords' from the security
settings of your CloudStor account here:
  https://cloudstor.aarnet.edu.au/plus/settings/personal?sectionid=security

PLEASE NOTE: If you snapshot this instance and share it, your CloudStor
app password may be exposed though the configuration file /etc/davfs2/secrets.
For more information, please see the CloudStor setup article at:
  https://support.ehelp.edu.au/support/solutions/articles/6000211327

EOF

# If username and password are set on the command line, then skip this line
if [ -z "${username}" ] || [ -z "${password}" ]; then
  echo "Press [ENTER] to continue or Ctrl+C to exit."
  read -r -s -n1 _
  echo
fi

# Package install
if [ -f '/etc/debian_version' ] ; then
  # Ubuntu/Debian
  if ! dpkg -s davfs2 >/dev/null 2>&1; then
    echo "Installing required packages..."
    sudo apt-get -y -qq update
    # Set suid for davfs for unprivileged mount
    echo "davfs2 davfs2/suid_file boolean true" | sudo debconf-set-selections
    DEBIAN_FRONTEND=noninteractive sudo apt-get -y -qq install davfs2
  fi
elif [ -f '/etc/fedora-release' ]; then
  # Fedora
  if ! rpm -q davfs2 >/dev/null 2>&1; then
    echo "Installing required packages..."
    sudo dnf install -y -q davfs2
  fi
elif [ -f '/etc/redhat-release' ]; then
  # CentOS
  if ! rpm -q davfs2 >/dev/null 2>&1; then
    echo "Installing required packages..."
    sudo yum -y -q install davfs2
  fi
else
    echo 'Unknown OS. This will only work on Ubuntu, Debian, CentOS or Fedora.'
    exit 1
fi

# Read username if not given on the command line
if [ -z "$username" ]; then
  read -r -p 'Username: ' username
  if [ -z "$username" ]; then
    echo "You must provide your username!"
    exit 1
  fi
fi

# Read password if not given on the command line
if [ -z "$password" ]; then
  read -s -r -p 'App password: ' password
  echo
  if [ -z "$password" ]; then
    echo "You must provide a password!"
    exit 1
  fi
fi

# Test credentials before modifying any files
echo -n "Testing your CloudStor credentials... "
statuscode=$(curl -sL -w "%{http_code}\\n" -u "$username:$password" "$WEBDAV_URL" -o /dev/null)
case $statuscode in
  200)
    echo "OK"
    ;;
  401|503)
    echo "Error!"
    echo "Authentication error when testing your CloudStor credentials."
    echo "Please check your credentials and try again later"
    exit 1
    ;;
  *)
    echo "Error!"
    echo "Unknown error when test your CloudStor credentials."
    exit 1
    ;;
esac

# Remove existing credentials if they exist
sudo sed -i '\,^'"$WEBDAV_URL"',d' /etc/davfs2/secrets

# Add new credentials -- note that we quote the password for davfs2, then
# escape any quotes within in the password itself.
# shellcheck disable=SC2001
escapedpassword=$(echo "$password" | sed 's/"/\\"/g')  # noqa
echo "$WEBDAV_URL $username \"$escapedpassword\"" | sudo tee -a /etc/davfs2/secrets > /dev/null

[ -d "$mount_path" ] || sudo mkdir "$mount_path"
if ! grep -q "$WEBDAV_URL" /etc/fstab; then
  echo "$WEBDAV_URL $mount_path davfs uid=$USER,_netdev 0 0" | sudo tee -a /etc/fstab > /dev/null
fi

# Explicitly disable locks - not supported by OwnCloud
sudo sed -i 's/.*use_locks.*/use_locks 0/g' /etc/davfs2/davfs2.conf

# Perform mount
echo -n "Mounting CloudStor storage... "
if sudo mount "$mount_path"; then
  echo "done"
  echo "Your CloudStor account has been mounted to $mount_path"
  exit 0
fi

echo
echo "There was an error mounting your CloudStor storage."
echo "For assistance, please copy the output of this command and submit"
echo "a ticket with our helpdesk at:"
echo "  support@ehelp.edu.au"
exit 1
