---
- name: Include OS-specific variables
  include_vars: "{{ vars_item }}"
  with_first_found:
    - "{{ ansible_facts['distribution'] | lower }}_{{ ansible_facts['distribution_major_version'] }}.yml"
    - "{{ ansible_facts['distribution'] | lower }}_{{ ansible_facts['distribution_release'] }}.yml"
    - "{{ ansible_facts['os_family'] | lower }}_{{ ansible_facts['distribution_major_version'] }}.yml"
    - "{{ ansible_facts['os_family'] | lower }}_{{ ansible_facts['distribution_release'] }}.yml"
    - "{{ ansible_facts['distribution'] | lower }}.yml"
    - "{{ ansible_facts['os_family'] | lower }}.yml"
  loop_control:
    loop_var: vars_item

- name: Include OS-specific tasks
  include_tasks: "{{ tasks_item }}"
  with_first_found:
    - "setup-{{ ansible_facts['distribution'] | lower }}.yml"
    - "setup-{{ ansible_facts['os_family'] | lower }}.yml"
  loop_control:
    loop_var: tasks_item
