---
- name: Install Ubuntu cloud archive keyring
  apt:
    name: ubuntu-cloud-keyring
    state: present
  when: openstack_clients_version is defined

- name: Add Ubuntu cloud archive repository
  deb822_repository:
    name: "cloudarchive-{{ openstack_clients_version }}"
    uris: http://ubuntu-cloud.archive.canonical.com/ubuntu
    suites: "{{ ansible_facts['distribution_release'] }}-updates/{{ openstack_clients_version }}"
    components: main
    signed_by: /usr/share/keyrings/ubuntu-cloud-keyring.gpg
  when: openstack_clients_version is defined

- name: Update apt cache
  apt:
    update_cache: true
  when: openstack_clients_version is defined

- name: Install OpenStack client packages
  package:
    name: "{{ openstack_clients_packages }}"
    state: present
