build_name        = "bumblebee-neurodesk"
os_name           = "ubuntu"
os_version        = "24.04"
os_arch           = "x86_64"
source_image_name = "NeCTAR Ubuntu 24.04 LTS (Noble) amd64"
ssh_username      = "ubuntu"
profile           = "bumblebee-neurodesk"
