build_name        = "bumblebee-guacamole"
os_name           = "ubuntu"
os_version        = "22.04"
os_arch           = "x86_64"
source_image_name = "NeCTAR Ubuntu 22.04 LTS (Jammy) amd64"
ssh_username      = "ubuntu"
profile           = "bumblebee-guacamole"
