---
- name: Add Nectar repositories
  deb822_repository:
    name: nectar
    uris: http://download.rc.nectar.org.au/nectar-ubuntu
    suites: "{{ ansible_facts['distribution_release'] }}"
    components: main
    signed_by: http://download.rc.nectar.org.au/nectar-archive-key-2016.gpg

- name: Update apt cache
  apt:
    update_cache: true

- name: Install packages
  package:
    name:
      - openssh-server
      - sudo
      - rpcbind
      - vim
      - iptables
      - inetutils-ping
      - net-tools
      - python3
      - qemu-guest-agent
      - curl
    state: present

- name: Install nfs packages
  package:
    name:
      - nfs-common
      - nfs-kernel-server
      - portmap
    state: present

# Create dummy share to allow running nfs-kernel-server before creating user shares
# NB: Upstream use different method to patch init script instead.
# See: https://github.com/openstack/manila-image-elements/blob/master/elements/ubuntu-nfs/post-install.d/50-manila-nfs-patch-config
- name: dummy share in /etc/exports file
  ansible.builtin.lineinfile:
    path: /etc/exports
    state: present
    line: '/mnt localhost(ro)'

- name: Install cifs packages
  package:
    name:
      - samba
      - samba-common
      - samba-common-bin
      - cifs-utils
    state: present

- name: Enable registry in samba config
  ini_file:
    path: /etc/samba/smb.conf
    section: global
    option: include
    value: registry
    mode: 0644
