---
- name: Download Guacamole OIDC auth plugin
  get_url:
    url: "https://archive.apache.org/dist/guacamole/{{ guacamole_version }}/binary/guacamole-auth-sso-{{ guacamole_version }}.tar.gz"
    dest: "/tmp/guacamole-auth-sso-{{ guacamole_version }}.tar.gz"
    mode: '0644'

- name: Extract Guacamole OIDC auth plugin
  unarchive:
    src: "/tmp/guacamole-auth-sso-{{ guacamole_version }}.tar.gz"
    dest: /tmp
    remote_src: yes

- name: Handle Jakarta EE Migration for Tomcat 10
  block:
    - name: Migrate Guacamole OIDC plugin to Jakarta EE
      command:
        cmd: >
          java -jar /tmp/jakartaee-migration.jar
          /tmp/guacamole-auth-sso-{{ guacamole_version }}/openid/guacamole-auth-sso-openid-{{ guacamole_version }}.jar
          /tmp/guacamole-auth-sso-openid-{{ guacamole_version }}-jakarta.jar
        creates: "/tmp/guacamole-auth-sso-openid-{{ guacamole_version }}-jakarta.jar"

    - name: Verify migrated OIDC plugin JAR
      command:
        cmd: unzip -tq /tmp/guacamole-auth-sso-openid-{{ guacamole_version }}-jakarta.jar

    - name: Use Jakarta OIDC plugin
      set_fact:
        guacamole_auth_openid_source: "/tmp/guacamole-auth-sso-openid-{{ guacamole_version }}-jakarta.jar"
  when: guacamole_tomcat_package == 'tomcat10'

- name: Use Standard OIDC plugin for Tomcat 9
  set_fact:
    guacamole_auth_openid_source: "/tmp/guacamole-auth-sso-{{ guacamole_version }}/openid/guacamole-auth-sso-openid-{{ guacamole_version }}.jar"
  when: guacamole_tomcat_package != 'tomcat10'

- name: Install Guacamole OIDC plugin
  copy:
    src: "{{ guacamole_auth_openid_source }}"
    dest: "/etc/guacamole/extensions/guacamole-auth-sso-openid-{{ guacamole_version }}.jar"
    remote_src: yes
    mode: '0644'
  notify: restart tomcat

- name: Clean up Guacamole OIDC auth plugin temp files
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/tmp/guacamole-auth-sso-{{ guacamole_version }}.tar.gz"
    - "/tmp/guacamole-auth-sso-{{ guacamole_version }}"
    - "/tmp/guacamole-auth-sso-openid-{{ guacamole_version }}-jakarta.jar"
