---
- name: Include OS-specific variables
  include_vars: "{{ var_item }}"
  with_first_found:
    - "{{ ansible_facts['distribution'] }}.yml"
    - "{{ ansible_facts['os_family'] }}.yml"
    - default.yml
  loop_control:
    loop_var: var_item

- name: Create facts and tags directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ fact_dir }}"
    - "{{ tag_dir }}"
  delegate_to: localhost
  become: false
  run_once: true

# Common facts we want to apply to all images
- ansible.builtin.include_tasks: facts.yml

# Prepare lists of dynamic keys we’ll use more than once
- name: Build list of nectar fact keys
  ansible.builtin.set_fact:
    nectar_fact_keys: "{{ query('varnames', '^nectar_image_property_.*') }}"

- name: Build list of nectar tag keys
  ansible.builtin.set_fact:
    nectar_tag_keys: "{{ query('varnames', '^nectar_image_tag_.*') }}"

# We lookup any facts starting with nectar_image_property_ and write them to files
- name: Save facts
  ansible.builtin.copy:
    content: "{{ lookup('vars', item) }}"
    dest: "{{ fact_dir }}/{{ item | regex_replace('^nectar_image_property_', '') }}"
    mode: "0644"
  loop: "{{ nectar_fact_keys }}"
  delegate_to: localhost
  become: false
  run_once: true

# Any values given as part of the image_properties var we'll also write as facts
- name: Save image properties
  ansible.builtin.copy:
    content: "{{ item.value }}"
    dest: "{{ fact_dir }}/{{ item.key }}"
    mode: "0644"
  loop: "{{ image_properties | dict2items }}"
  delegate_to: localhost
  become: false
  run_once: true

# We lookup any tags starting with nectar_image_tag_ and write them to files
- name: Save tags
  ansible.builtin.copy:
    content: ""
    dest: "{{ tag_dir }}/{{ item | regex_replace('^nectar_image_tag_', '') }}"
    mode: "0644"
  loop: "{{ nectar_tag_keys }}"
  delegate_to: localhost
  become: false
  run_once: true

- name: Print facts
  ansible.builtin.debug:
    msg: "{{ item | regex_replace('^nectar_image_property_', '') }} = {{ lookup('vars', item) }}"
  loop: "{{ nectar_fact_keys }}"
  run_once: true

- name: Print image properties
  ansible.builtin.debug:
    msg: "{{ item.key }} = {{ item.value }}"
  loop: "{{ image_properties | dict2items }}"
  run_once: true
