---
- name: restart xrdp
  service:
    name: xrdp
    state: restarted

- name: restart sesman
  service:
    name: xrdp-sesman
    state: restarted

- name: reload systemd
  systemd:
    daemon_reload: yes
