---
nectar_default_image_name: "{{ ansible_facts['distribution'] }} {{ ansible_facts['architecture2'] }}"

facts_architecture: "{{ ansible_facts['architecture2'] }}"
facts_os_distro: "{{ ansible_facts['os_family']|lower }}"
facts_os_version: "2022"
facts_nectar_name: "{{ nectar_name }}"
