---
- name: Add cloud-init config file
  template:
    src: cloud.cfg.j2
    dest: /etc/cloud/cloud.cfg

- name: Detect sudo implementation
  command: sudo --version
  register: sudo_version_output
  changed_when: false

# New sudo-rs in Ubuntu 26.04 doesn't support the requiretty option
- name: Don't requiretty for sudo (Legacy C-Sudo only)
  lineinfile:
    dest: /etc/sudoers
    line: "Defaults !requiretty"
    validate: 'visudo -cf %s'
  when: "'sudo-rs' not in sudo_version_output.stdout"

- name: Get cloud-init version
  shell: "cloud-init --version 2>&1 | awk '{print $NF}'"
  register: cloudinit_version

- debug:
    msg: "cloud-init version is {{ cloudinit_version.stdout }}"

- block:
  - name: Find cloud-init DHCP file
    shell: 'ls /usr/lib/python*/*-packages/cloudinit/net/dhcp.py'
    register: cloudinit_dhcp_file

  # Fix for https://bugs.launchpad.net/bugs/1821102 until 19.2 is released.
  - name: Ephemeral DHCP fix
    lineinfile:
      path: "{{ cloudinit_dhcp_file.stdout }}"
      insertafter: '^    def __enter__\(self\):'
      line: '        raise NoDHCPLeaseError()  # Nectar disabling Ephemeral'
      firstmatch: yes
      state: present
      backup: yes
  when:
    - cloudinit_version.stdout is version_compare('18.2', '>')
    - cloudinit_version.stdout is version_compare('19.2', '<')
