---
- name: Include OS-specific variables
  include_vars: "{{ var_item }}"
  with_first_found:
    - "{{ ansible_facts['distribution'] }}_{{ ansible_facts['distribution_version'] }}.yml"
    - "{{ ansible_facts['distribution'] }}_{{ ansible_facts['distribution_major_version'] }}.yml"
    - "{{ ansible_facts['distribution'] }}.yml"
    - "{{ ansible_facts['os_family'] }}.yml"
    - default.yml
  loop_control:
    loop_var: var_item

- include_tasks: install.yml
- include_tasks: config.yml
- include_tasks: services.yml
